### ISSUE TITLE
TestMain.java is empty and incompleted.

### ISSUE THREAD

**Issue by andHW** [Kelvin0v0/CS3343#11]
**Expected Result**
A completed test on Main.java file.

**Actual Result**
Only 20 lines of code unrelated to Main.java are there.

![image](https://user-images.githubusercontent.com/45086238/69908687-b3254400-1429-11ea-94a7-c14455560692.png)

**Comment by antonychoi1129** [comment]
main is not testable and it is meaning less to test main

**Comment by andHW** [comment]
Then we should remove it.
