### ISSUE TITLE
Weird Menu behaviour. No feedback after wrong input.

### ISSUE THREAD

**Issue by andHW** [Kelvin0v0/CS3343#3]
When inputting 4, nothing happens. The behaviour is weird.
When inputting other characters, the menu has no feedback at all.

Expected Result:
The blank item should not appear in the menu list.
Reasonable feedback after the wrong option is entered.

Actual Result:
Blank item appears.
No feedbacks at all

Screenshot:
![WhatsApp Image 2019-11-08 at 1 23 36 PM](https://user-images.githubusercontent.com/45086238/68451779-122cda00-022b-11ea-9276-65d617cb805f.jpeg)
.

**Comment by antonychoi1129** [comment]
4 is for the slot machine, we did not finish at that time. Now finished.
The problem of no feedback when entering a wrong input is fixed.
