### ISSUE TITLE
Menu Typo and name validation is missing.

### ISSUE THREAD

**Issue by andHW** [Kelvin0v0/CS3343#5]
youe -> your

Expected Results:

1. "What's your name:"

2. Blank name should not be accepted.

Actual Results:

1. Typo

2. Blank name is accepted.

![image](https://user-images.githubusercontent.com/45086238/69496852-9365bb80-0f11-11ea-8c26-0744663bb550.png)

**Comment by Kelvin0v0** [comment]
Thx. We will fix it later
