### ISSUE TITLE
The UI is inconsistent in different games

### ISSUE THREAD

**Issue by andHW** [Kelvin0v0/CS3343#8]
As title.

**Comment by Kelvin0v0** [comment]
May you detailly tell us the location or url. please.

**Comment by andHW** [comment]
Examples:

1. The letter case for the same option in menus are different
- **Slot Machine** use 'q'
- some of the **other games** use 'Q'
- **Blackjack** uses Y/N

2. Quitting Behaviour
- **Slot machine** quit smoothly
- **Other games** have to press another enter to fully quit to the main menu

3. Ascii art in game's menus
**Roulette** and **Slot Machine** have no ASCII art in their menus.
