### ISSUE TITLE
Possible wrong location and naming of test files

### ISSUE THREAD

**Issue by andHW** [Kelvin0v0/CS3343#9]
**Expected Result**
TestBackJack.java should not exist as a separate group.

**Actual Result**
While all the other test files are located in the same group, TestBlackJack.java is uniquely out of there.

**Possible Solution**
Move TestBackJack.java in the default package (same as the rest); OR,
separate all games into a different group of folders.

![image](https://user-images.githubusercontent.com/45086238/69908579-b7e8f880-1427-11ea-97d6-4dcf9dfb1eee.png)

**Comment by miketsui3a** [comment]
done
